type Factory @entity {
  id: ID!
  totalStaked: BigInt!
  totalPendingWithdrawal: BigInt!
  numOfCandidate: BigInt!
}

type Candidate @entity {
  # candidate index
  id: Bytes!
  candidate: Bytes!
  candidateContract: Bytes! # address
  name: String! # string
  #blockNumber: BigInt!
  #blockTimestamp: BigInt!
	#owner: Bytes!
  #coinage: Bytes!
	# staked amount of this candidate
	stakedAmount: BigInt!
  pendingWithdrawalAmount: BigInt!
  #txCount: BigInt!
  commissionRate: BigDecimal!
  # user info who are staking to this candidate
	user: [User!]
  # derived values
  staked: [Staked]! @derivedFrom(field: "candidate")
  unstaked: [Unstaked]! @derivedFrom(field: "candidate")
  restaked: [Restaked]! @derivedFrom(field: "candidate")
	withdrawal: [Withdrawal]! @derivedFrom(field: "candidate")
}

type User @entity {
	# user address
  id: ID!
	# deposited amount of this user
	totalStaked: BigInt!
  pendingWithdrawalAmount: BigInt!
	# amount of TON from seigniorage 
	totalEarnedSeig: BigInt!
  userStaked: [UserStaked!]!
	# derived values
  staked: [Staked]! @derivedFrom(field: "user")
  unstaked: [Unstaked]! @derivedFrom(field: "user")
  restaked: [Restaked]! @derivedFrom(field: "user")
	withdrawal: [Withdrawal]! @derivedFrom(field: "user")
}

type UserStaked @entity {
  id: ID!
  # user address
  user: User!
  # index of candidate
  candidateAddress: Candidate!
  stakedAmount: BigInt!
  pendingWithdrawalAmount: BigInt!
}

type Transaction @entity {
  # txn hash
  id: ID!
  # block txn was included in
  blockNumber: BigInt!
  # timestamp txn was confirmed
  timestamp: BigInt!
  # gas used during txn execution
  gasUsed: BigInt!
  gasPrice: BigInt!
  # derived values
  staked: [Staked]! @derivedFrom(field: "transaction")
  unstaked: [Unstaked]! @derivedFrom(field: "transaction")
  restaked: [Restaked]! @derivedFrom(field: "transaction")
	withdrawal: [Withdrawal]! @derivedFrom(field: "transaction")
}

type Staked @entity(immutable: true) {
  id: ID!
  transaction: Transaction!
  timestamp: BigInt!
  
  candidate: Candidate!
  user: User!
  sender: Bytes! # address
  amount: BigInt! # uint256
  lton: BigInt! # uint256
  commissionTo: Bytes! # address
  commission: Int! # uint16
}

type Unstaked @entity(immutable: true) {
  id: ID!
  transaction: Transaction!
  timestamp: BigInt!
  
  candidate: Candidate!
  user: User!
  sender: Bytes! # address
  amount: BigInt! # uint256
  lton: BigInt! # uint256
}

type Restaked @entity(immutable: true) {
  id: ID!
  transaction: Transaction!
  timestamp: BigInt!
  
  candidate: Candidate!
  user: User!
  sender: Bytes! # address
  amount: BigInt! # uint256
  lton: BigInt! # uint256
}

type Withdrawal @entity(immutable: true) {
  id: ID!
  transaction: Transaction!
  timestamp: BigInt!
  
  candidate: Candidate!
  user: User!
  sender: Bytes! # address
  amount: BigInt! # uint256
}

type Comitted @entity(immutable: true) {
  id: Bytes!
  layer2: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type CommissionRateSet @entity(immutable: true) {
  id: Bytes!
  layer2: Bytes! # address
  previousRate: BigInt! # uint256
  newRate: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}


type OnSnapshot @entity(immutable: true) {
  id: Bytes!
  snapshotId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SeigGiven @entity(immutable: true) {
  id: Bytes!
  layer2: Bytes! # address
  totalSeig: BigInt! # uint256
  stakedSeig: BigInt! # uint256
  unstakedSeig: BigInt! # uint256
  powertonSeig: BigInt! # uint256
  pseig: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdatedSeigniorage @entity(immutable: true) {
  id: Bytes!
  layer2: Bytes! # address
  blockNumber: BigInt! # uint256
  prevTotal: BigInt! # uint256
  nextTotal: BigInt! # uint256
  oldTotFactor: BigInt! # uint256
  oldCoinageFactor: BigInt! # uint256
  nextTotFactor: BigInt! # uint256
  nextCoinageFactor: BigInt! # uint256
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
